version: '3'
services:
  db:
    build: docker/db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d